### ISSUE TITLE
V2.1.0: Error when OpenArchieven is activated (with wt2.0.23)

### ISSUE THREAD

**Issue by ungeahnt** [JustCarmen/webtrees-fancy-research-links#55]
`Too few arguments to function JustCarmen\Webtrees\Module\FancyResearchLinks\Plugin\OpenArchievenPlugin::researchLink(), 1 passed in …/modules_v4/jc-fancy-research-links/resources/views/sidebar.phtml on line 41 and exactly 3 expected …/modules_v4/jc-fancy-research-links/plugins/OpenArchievenPlugin.php:27
#0 …/modules_v4/jc-fancy-research-links/resources/views/sidebar.phtml(41): JustCarmen\Webtrees\Module\FancyResearchLinks\Plugin\OpenArchievenPlugin::researchLink(Array)
#1 …/app/View.php(184): include('/home/www/proav...')
#2 …/app/View.php(281): Fisharebest\Webtrees\View->render()
#3 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make('_jc-fancy-resea...', Array)
#4 …/modules_v4/jc-fancy-research-links/FancyResearchLinksModule.php(262): view('_jc-fancy-resea...', Array)
#5 …/resources/views/individual-page.phtml(149): JustCarmen\Webtrees\Module\FancyResearchLinks\FancyResearchLinksModule->getSidebarContent(Object(Fisharebest\Webtrees\Individual))
#6 …/app/View.php(184): include('/home/www/proav...')
#7 …/app/View.php(281): Fisharebest\Webtrees\View->render()
#8 …/app/Helpers/functions.php(200): Fisharebest\Webtrees\View::make('individual-page', Array)
#9 …/app/Http/ViewResponseTrait.php(51): view('individual-page', Array)
...
`

**Comment by ungeahnt** [comment]
see #50
